name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S . -A Win32

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build -C Release --output-on-failure
